# Generated by Django 4.0 on 2021-12-27 22:22

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import resume.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resume', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('content', ckeditor.fields.RichTextField()),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('file', models.FileField(upload_to='projects/', validators=[resume.models.validate_zip_rar_file])),
                ('cover', models.FileField(upload_to='images/project_cover/', validators=[resume.models.validate_jpg_png_file])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.userprofile')),
                ('category', models.ManyToManyField(to='resume.Category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
